# Generated by Django 3.2.5 on 2021-07-26 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stackoverflowapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField()),
                ('last_time_search', models.DateTimeField()),
                ('num_of_query', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
